### ISSUE TITLE
Screenshot bug

### ISSUE THREAD

**Issue by tsunyoku** [tsunyoku/Asahi#15]
Not quite sure what the cause is, as you can see below it does handle jpg/png detection:

https://github.com/tsunyoku/Asahi/blob/e27c29a58429ed74859145b6fcaaaab40f17726f/endpoints/web.py#L75-L83

Uploaded screenshots don't seem to show properly in the web browser, the bottom half will appear white. An example can be seen here: https://osu.tsunyoku.xyz/ss/NQVJTRC6.jpeg

It is definitely not related to the saving of the screenshot as if you pull the screenshot directly from the server, it appears fine.
I'm assuming it's some form of header issue however throughout testing I haven't found any fix.

Any help is appreciated!

**Comment by tsunyoku** [comment]
I've just tried to add a Content-Type header to the screenshot endpoint here

https://github.com/tsunyoku/Asahi/blob/e27c29a58429ed74859145b6fcaaaab40f17726f/endpoints/web.py#L89

which still didn't alleviate the issue. This is the code I tried:

```
    type = scr.split('.')[1]

    if ss.exists():
        request.resp_headers['Content-Type'] = f'image/{type}'
```

**Comment by atteure** [comment]
This looks more like an issue of the server trying to show the screenshot instead of the image itself being saved onto the server; I'd have no idea what the problem is though

**Comment by tsunyoku** [comment]
![image](https://user-images.githubusercontent.com/51536154/124105121-ce6b9180-da5a-11eb-97b1-92c5b331198d.png)

Current problem is a Content-Length mismatch, I have a feeling it might be related to NGINX cache but not sure...

**Comment by RealistikDash** [comment]
Can you check if the screenshot saved is ok

**Comment by tsunyoku** [comment]
![image](https://user-images.githubusercontent.com/51536154/124365974-e0f4ef00-dc43-11eb-97e0-576a96cf6ecd.png)

no words.

**Comment by tsunyoku** [comment]
didn't fix it regardless.

**Comment by atteure** [comment]
TROLLED

**Comment by tsunyoku** [comment]
randomly working again, idfk at this point but closing for now

**Comment by 7ez** [comment]
your mum

**Comment by tsunyoku** [comment]
Broken again ASDHFUIASDIHUFASDHIUF

**Comment by 7ez** [comment]
trolled.

**Comment by tsunyoku** [comment]
it was my fucking vps i give up
