### ISSUE TITLE
auth trouble

### ISSUE THREAD

**Issue by GoGixdd** [tsunyoku/Asahi#26]
When i register an account everything goes fine.
But authorization does nothing. What could be wrong? 
https://jojik.pls-finger.me/55tLFpqkY - login
https://jojik.pls-finger.me/55tLPNCcS - register

**Comment by RealistikDash** [comment]
In nginx, did you route `c.your.domain` to asahi too?

**Comment by GoGixdd** [comment]
Where i can do it?

**Comment by GoGixdd** [comment]
![image](https://user-images.githubusercontent.com/25837840/127324128-1fb84bdd-56a1-46ea-a13d-5f9309cdd49e.png)
yes

**Comment by GoGixdd** [comment]
![image](https://user-images.githubusercontent.com/25837840/127325302-fde29cc3-f6e9-4981-93ad-5a3e7db47374.png)
Also, i think something wrong with password hashing...

**Comment by tsunyoku** [comment]
> ![image](https://user-images.githubusercontent.com/25837840/127325302-fde29cc3-f6e9-4981-93ad-5a3e7db47374.png)
> Also, i think something wrong with password hashing...

surprisingly, its supposed to look like this

**Comment by tsunyoku** [comment]
> https://jojik.pls-finger.me/55wR_ZmFD
> yes, i did it in asahi.conf

is this config file in the folder `/etc/nginx/sites-enabled` and did you reload nginx after it was put there?

**Comment by tsunyoku** [comment]
and by auth trouble do you mean connection failed or is it saying incorrect password?

**Comment by GoGixdd** [comment]
it's can register account, but auth has error 
![image](https://user-images.githubusercontent.com/25837840/127327884-8e3ecd96-34d1-4c6d-826b-0883fc8f2477.png)

**Comment by tsunyoku** [comment]
can you restart the server and try to login again? when someone registers it adds their password to cache and i wonder if i did that incorrectly

**Comment by GoGixdd** [comment]
nothing changed 
https://jojik.pls-finger.me/55w_EcyeK

**Comment by tsunyoku** [comment]
are you using up to date asahi? the incorrect password message is different in asahi code, unless you edited it

**Comment by GoGixdd** [comment]
yes, it's up to date version, but i added my logger 
web.py & players.py:
![image](https://user-images.githubusercontent.com/25837840/127329961-415d2e8a-869a-4ae6-84a2-1c3eb049b6da.png)
![image](https://user-images.githubusercontent.com/25837840/127330056-b454f0a6-b6ec-4e0a-9f47-ac82c03c4cc2.png)

**Comment by tsunyoku** [comment]
find_login is for finding a user by their password after they have logged in… if you aren’t able to login then that is why, the original login code must stay the same

**Comment by tsunyoku** [comment]
and the auth function is also for after the user has logged in, /web/ endpoints provide the username and password hash and then uses find_login to find the user with them

**Comment by GoGixdd** [comment]
![image](https://user-images.githubusercontent.com/25837840/127330616-9a31e1b0-f7a1-4e65-9fa4-ffdd4d1ee89f.png)
after press login button:

**Comment by tsunyoku** [comment]
it isnt showing any request in your console which means there must be some dns error. make sure you have c4, ce and c subdomains in both your nginx config and your domain’s dns or its not going to work

**Comment by GoGixdd** [comment]
We have only  c. , osu. , api

**Comment by tsunyoku** [comment]
the nginx has all of the ones it needs from the screenshot i saw so ill leave the nginx. in your dns you need:

c
c4
ce
a
osu
api
b
s
assets

**Comment by GoGixdd** [comment]
okay, i will try adding same subdomains..

**Comment by GoGixdd** [comment]
all subdomains were added + full reinstall Asahi server. 
Nothing changed.
https://jojik.pls-finger.me/55yaOZlpT.png

**Comment by tsunyoku** [comment]
this still isn't an asahi issue as asahi isnt getting any bancho requests, i cannot help you

**Comment by GoGixdd** [comment]
solution  - downgrade to ubuntu 18.04
