### ISSUE TITLE
can i use Asahi without redis 

### ISSUE THREAD

**Issue by Zordon1337** [tsunyoku/Asahi#34]
because i get this
![image](https://user-images.githubusercontent.com/65111609/160869719-87f66d27-2f6f-4832-9c3a-3afda20d0e41.png)

**Comment by tsunyoku** [comment]
`python3.9 -m pip install aioredis==1.3.1` will fix this

**Comment by 7ez** [comment]
python3.9 -m pip install aioredis==1.3.9

**Comment by 7ez** [comment]
psure i fixed that in requirements though

**Comment by 7ez** [comment]
I did

**Comment by 7ez** [comment]
fix ur nginx config.

**Comment by tsunyoku** [comment]
> works but i have another problem ![image](https://user-images.githubusercontent.com/65111609/160876875-b282fed3-5926-4c8a-b4e0-6f078bfca934.png)

configurate your nginx.

**Comment by Bajgerek** [comment]
> 

i configured 
![image](https://user-images.githubusercontent.com/65111609/160890430-90b2978b-185f-4118-b1b1-46fa35495534.png)

**Comment by 7ez** [comment]
https://github.com/tsunyoku/Asahi/blob/main/README.md#L12

**Comment by tsunyoku** [comment]
> i configured
> ![image](https://user-images.githubusercontent.com/65111609/160890430-90b2978b-185f-4118-b1b1-46fa35495534.png)

make sure this file is in /etc/nginx/sites-enabled and you have reloaded nginx once it’s there

**Comment by Bajgerek** [comment]
![image](https://user-images.githubusercontent.com/65111609/160893593-5b0f4b8b-f11c-45ad-9b5b-a28e23b30acf.png)
and reloaded nginx

**Comment by Bajgerek** [comment]
but still nginx page
